import type { MenuResponse } from '../shared/schemas'

const timestamp = '2026-07-20T12:00:00.000Z'

export function publicMenuFixture(): MenuResponse {
  return {
    business: {
      id: 1,
      name: 'Lanchonete <Especial>',
      slug: 'lanchonete-especial',
      slogan: 'Feito na hora',
      description: 'Lanches e porções.',
      whatsapp: '5547999999999',
      phone: null,
      instagramUrl: 'https://instagram.com/lanchonete',
      facebookUrl: null,
      address: 'Rua das Flores, 10',
      addressPostalCode: '88100-000',
      addressStreet: 'Rua das Flores',
      addressNumber: '10',
      addressComplement: null,
      addressNeighborhood: 'Centro',
      addressCity: 'São José',
      addressState: 'SC',
      mapsUrl: null,
      timezone: 'America/Sao_Paulo',
      specialMessage: 'Hoje tem promoção.',
      primaryColor: '#FB5D01',
      coverImageKey: 'covers/123e4567-e89b-12d3-a456-426614174000.webp',
      faviconKey: 'favicons/123e4567-e89b-12d3-a456-426614174000.ico',
      publicSiteUrl: 'https://cardapio.exemplo.com.br',
      seoTitle: null,
      seoDescription: null,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    hours: Array.from({ length: 7 }, (_, weekday) => ({
      id: `hour-${weekday}`,
      weekday,
      opensAt: '18:00',
      closesAt: '23:00',
      isClosed: false,
      sortOrder: weekday,
    })),
    paymentMethods: [{ id: 'payment-1', name: 'Pix', isActive: true, sortOrder: 0 }],
    deliveryZones: [{ id: 'zone-1', name: 'Centro', feeCents: 500, notes: null, isActive: true, sortOrder: 0 }],
    categories: [{
      id: 'category-1',
      name: 'Lanches',
      slug: 'lanches',
      description: 'Nossos lanches',
      isActive: true,
      sortOrder: 0,
      createdAt: timestamp,
      updatedAt: timestamp,
      products: [{
        id: 'product-1',
        categoryId: 'category-1',
        name: 'X-Salada',
        ingredients: 'Pão, carne e salada',
        imageKey: null,
        isAvailable: true,
        isFeatured: false,
        sortOrder: 0,
        createdAt: timestamp,
        updatedAt: timestamp,
        variants: [{
          id: 'variant-1',
          label: null,
          priceCents: 2590,
          promotionalPriceCents: null,
          isActive: true,
          sortOrder: 0,
        }],
      }],
    }],
  }
}
